// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gee
Rcpp::List gee(const arma::vec y, const arma::mat X, const arma::uvec clusterSizes, const Rcpp::List family_objs);
RcppExport SEXP _geeq_gee(SEXP ySEXP, SEXP XSEXP, SEXP clusterSizesSEXP, SEXP family_objsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type clusterSizes(clusterSizesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type family_objs(family_objsSEXP);
    rcpp_result_gen = Rcpp::wrap(gee(y, X, clusterSizes, family_objs));
    return rcpp_result_gen;
END_RCPP
}
// pgee
Rcpp::List pgee(const arma::vec y, const arma::mat X, const arma::uvec clusterSizes, const Rcpp::List family_objs, const arma::uvec pindex, double lambda);
RcppExport SEXP _geeq_pgee(SEXP ySEXP, SEXP XSEXP, SEXP clusterSizesSEXP, SEXP family_objsSEXP, SEXP pindexSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type clusterSizes(clusterSizesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type family_objs(family_objsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec >::type pindex(pindexSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(pgee(y, X, clusterSizes, family_objs, pindex, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geeq_gee", (DL_FUNC) &_geeq_gee, 4},
    {"_geeq_pgee", (DL_FUNC) &_geeq_pgee, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_geeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
