// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "gee.h"


RcppExport SEXP _gee(SEXP ys, SEXP Xs, SEXP clusterSizes, SEXP family_objs) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;

    arma::mat X = Rcpp::as<arma::mat>(Xs);
    arma::vec y = Rcpp::as<arma::vec>(ys);
    arma::uvec cs = Rcpp::as<arma::uvec>(clusterSizes);
    Family family(Rcpp::as<Rcpp::List>(family_objs));

    RO result = gee_iteration(X, y, cs, family, AR1, 20);
    Rcpp::List return_obj = Rcpp::List::create(Rcpp::Named("beta")=result.beta,
                                               Rcpp::Named("alpha")=result.alpha,
                                               Rcpp::Named("phi")=result.phi);
    rcpp_result_gen = Rcpp::wrap(return_obj);
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gee", (DL_FUNC) &_gee, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_anRpackage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}