# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gee <- function(y, X, clusterSizes, family_objs) {
    .Call(`_geeq_gee`, y, X, clusterSizes, family_objs)
}

