# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pgee_c <- function(Y, X, offset, cluster_sizes, family_objs, corstr, init_beta, init_alpha, init_phi, scale_fix, lambda, pindex, eps, maxit, tol) {
    .Call(`_geeq_pgee_c`, Y, X, offset, cluster_sizes, family_objs, corstr, init_beta, init_alpha, init_phi, scale_fix, lambda, pindex, eps, maxit, tol)
}

gee_c <- function(Y, X, offset, cluster_sizes, family_objs, corstr, init_beta, init_alpha, init_phi, scale_fix, maxit, tol) {
    .Call(`_geeq_gee_c`, Y, X, offset, cluster_sizes, family_objs, corstr, init_beta, init_alpha, init_phi, scale_fix, maxit, tol)
}

qif_c <- function(Y, X, offset, cluster_sizes, family_objs, corstr, init_beta) {
    .Call(`_geeq_qif_c`, Y, X, offset, cluster_sizes, family_objs, corstr, init_beta)
}

